service: todo-rest-api-nest-sls

plugins:
  - serverless-layers
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  memorySize: 256
  logRetentionInDays: 1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    LANG: ja_JP.UTF-8
    AUTH_SECRET: ${ssm:/dafujii/todo-rest-api-nest-sls/AUTH_SECRET}
  versionFunctions: false
  deploymentBucket:
    name: dafujii-serverless-deploymentbucket

package:
  individually: true
  include:
    - dist/**
  exclude:
    - "**"
functions:
  index:
    handler: dist/handler.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any
